//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MaerskLine.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Booking
    {
        public string BookingID { get; set; }
        public string CustID { get; set; }
        public string ShippingID { get; set; }
        public string Date { get; set; }
    
        public virtual Customer Customer { get; set; }
        public virtual Shipping Shipping { get; set; }
    }
}
